/// Flutter icons Weight_final
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Weight_final
///      fonts:
///       - asset: fonts/Weight_final.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Weight_final {
  Weight_final._();

  static const _kFontFam = 'Weight_final';
  static const _kFontPkg = null;

  static const IconData weight_final = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
